version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "dotnet-deploy"
region = "ap-northeast-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
parameter_overrides = "Environment=\"development\""

[staging.deploy]
[staging.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
stack_name = "staging-dotnet-deploy"
s3_bucket = "sam-dotnet-deploy-lambda-function"

[production.deploy]
[production.deploy.parameters]
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
stack_name = "production-dotnet-deploy"
s3_bucket = "sam-dotnet-deploy-lambda-function"
